# Generated by Django 5.2.17 on 2026-09-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dry_fruits', 'Dry Fruits'), ('seeds', 'Seeds'), ('namkeen', 'Namkeen')], default='dry_fruits', max_length=20),
        ),
    ]
